// data.jsx — real LainDOS content: nav tracks, boot stages, memory map.
// Boot-path source excerpts and line numbers reflect the current state of
// src/boot.asm and src/kernel.asm in this repository (CC0).
// Page-specific tracks keep their own excerpts with their page data.

// ---------- left-nav tracks ----------
const NAV = [
  { id: "overview", label: "Overview", kind: "page" },
  {
    id: "boot", label: "The Boot Path", kind: "track", status: "done",
    blurb: "Power-on to a running game, step by step",
    children: [
      ["s0", "Power-on & BIOS"],
      ["s1", "The 512-byte boot sector"],
      ["s2", "The kernel relocates"],
      ["s3", "Bring-up: serial, VGA, memory"],
      ["s4", "Installing the interrupts"],
      ["s5", "Memory arena & filesystem"],
      ["s6", "Finding & sizing the program"],
      ["s7", "Handoff — the game runs"],
    ],
  },
  { id: "dosapi", label: "The DOS API · INT 21h", kind: "track", status: "done",
    blurb: "What DOS API coverage means for games and tools" },
  { id: "tests", label: "Tests · Regression Ladder", kind: "track", status: "done",
    blurb: "How to add repros, QEMU runs, and game smokes" },
  { id: "fs", label: "Filesystem · FAT12/16", kind: "track", status: "done",
    blurb: "Cluster chains, directories, 8.3 names" },
  { id: "mem", label: "Memory · MCB / XMS", kind: "track", status: "done",
    blurb: "The MCB arena and extended-memory shims" },
  { id: "prog", label: "Programs · PSP / EXE / COM", kind: "track", status: "done",
    blurb: "Loading, relocating and EXEC-ing real programs" },
  { id: "shell", label: "Shell / Batch / PATH", kind: "track", status: "done",
    blurb: "Prompts, AUTOEXEC, commands and environment lookup" },
  { id: "mouse", label: "Mouse / INT 33h", kind: "track", status: "done",
    blurb: "PS/2 packets, callbacks, buttons and game input" },
  { id: "emulators", label: "Emulators / Debugging", kind: "track", status: "done",
    blurb: "QEMU, 86Box, Bochs, v86, and real-DOS comparisons" },
  { id: "glossary", label: "Glossary", kind: "page" },
  { id: "run", label: "Run it", kind: "run" },
];

// ---------- segment memory map (from src/memory.inc + boot.asm + README) ----------
const MEMMAP = [
  { seg: "FFFF", name: "Relocated kernel (HMA)", note: "HMA_SEG:0010 — stack top at FFF0h, A20 kept on", key: "kernel" },
  { seg: "A000", name: "VGA graphics memory", note: "MEM_TOP — mode 13h framebuffer", key: "vga" },
  { seg: "0640", name: "Program + environment arena", note: "MCB_START — where games live", key: "arena", grow: true },
  { seg: "0240", name: "Root directory buffer", note: "ROOT_SEG", key: "root" },
  { seg: "0220", name: "Read cache buffer", note: "READ_CACHE_BUF", key: "cache" },
  { seg: "0200", name: "Sector buffer", note: "SEC_BUF", key: "sec" },
  { seg: "0180", name: "CD-ROM sector buffer", note: "CD_BUF", key: "cd" },
  { seg: "0060", name: "FAT scratch buffer", note: "FAT_SEG", key: "fat" },
  { seg: "0040", name: "BIOS Data Area", note: "tick count, equipment word", key: "bda" },
  { seg: "0000", name: "Interrupt Vector Table", note: "256 far pointers", key: "ivt" },
];

// ---------- the boot narrative ----------
const STAGES = [
  {
    id: "s0", num: "00", file: "—", kicker: "Reset vector",
    title: "Power-on & BIOS",
    prose: [
      "When an x86 powers on it can't run a program yet — there's nothing in RAM. The CPU starts executing at the reset vector (physical FFFF0h, the top of the 1 MiB real-mode space), which is a far jump into the motherboard ROM. That ROM is the BIOS.",
      "The BIOS runs POST (counts RAM, initialises the PIC, PIT and video), then bootstraps: it reads the first 512-byte sector of the boot disk to physical 0x7C00, checks that its last two bytes are 55 AA, and far-jumps to it. The only thing it hands you in a register is DL — the drive you booted from.",
    ],
    code: null,
    annotations: [
      ["AA55", "The boot signature the BIOS checks at offset 510. boot.asm ends with `times 510-($-$$) db 0` then `dw 0xAA55` to guarantee it."],
      ["DL", "00h = floppy A:, 80h = first hard disk. boot.asm reads it immediately because the BIOS doesn't preserve it for long."],
    ],
    regs: [
      ["CS:IP", "0000:7C00", "where the boot sector starts"],
      ["DL", "00h / 80h", "boot drive (only reliable input)"],
      ["others", "undefined", "DS, ES, SS, SP must be set by us"],
    ],
    touches: ["ivt", "bda"],
    note: "DL = boot drive · CS:IP = 0000:7C00",
  },
  {
    id: "s1", num: "01", file: "src/boot.asm", kicker: "Establishing a stack",
    title: "The boot sector takes over",
    prose: [
      "We're now executing 512 bytes at 0x7C00 with no operating system underneath us — we have to build a sane machine state from scratch before doing anything else. That means: turn off interrupts, point all the segment registers somewhere known, and set up a stack.",
      "Real-mode addresses are segment:offset, where the linear address is segment×16 + offset. Zeroing DS/ES/SS makes every address we write a flat offset from 0, which keeps the arithmetic in this tiny sector simple.",
    ],
    code: [
      [68, "boot:"],
      [69, "    cli                ; no interrupts during setup"],
      [70, "    xor ax,ax"],
      [71, "    mov ds,ax"],
      [72, "    mov es,ax"],
      [73, "    mov ss,ax"],
      [74, "    mov sp,0x7C00      ; stack grows down from us"],
      [75, "    sti"],
      [76, "    cld                ; string ops count upward"],
      [77, "    mov [drv],dl       ; remember the boot drive"],
    ],
    hi: [74, 77],
    annotations: [
      [32, "cli clears the interrupt flag (IF=0). Between loading SS and SP the stack is momentarily inconsistent; an interrupt firing there would push onto a garbage stack, so we mask them."],
      [33, "xor ax,ax is the idiomatic two-byte way to zero a register. You can't `mov ds, 0` directly — segment registers only load from another register, so AX is the courier."],
      [37, "SP set to 0x7C00 means the stack grows downward from just below our code (pushes decrement SP), so it never overwrites the 512 bytes living at 0x7C00–0x7DFF."],
      [39, "cld clears the direction flag (DF=0) so lodsb / movsb / cmpsb auto-increment SI and DI — the boot sector relies on this for its string compares and copies."],
      [40, "DL is copied into a local variable (and to fixed address 0x500) so the value survives the BIOS calls to come, which clobber it."],
    ],
    regs: [
      ["DS / ES / SS", "0000", "flat addressing from zero"],
      ["SP", "7C00", "stack below the boot code"],
      ["IF", "1", "interrupts back on after setup"],
      ["DF", "0", "string ops increment"],
    ],
    touches: ["ivt"],
    note: "SS:SP = 0000:7C00 · [drv] = DL",
  },
  {
    id: "s1b", num: "01b", file: "src/boot.asm", kicker: "FAT12 by hand",
    title: "…and loads the kernel off the floppy",
    prose: [
      "There's no file system driver yet, so the boot sector is one. Using the BIOS Parameter Block baked into its own first bytes, it reads the FAT to segment 0x60 and the root directory to 0x0A20, then scans 32-byte directory entries for the 8.3 name \"KERNEL  SYS\". That 0x0A20 copy is boot-sector staging; the relocated kernel later reloads active root directories into ROOT_SEG at 0x0240.",
      "Once found, it follows the file's cluster chain. FAT12 packs each 12-bit entry across byte boundaries, so fat_next reads a word and shifts by 4 bits for odd clusters. Each cluster is read with INT 13h to LOAD_SEG (0x1000); when the chain hits an end-of-chain marker (≥ 0xFF8) it jumps in.",
    ],
    code: [
      [133, "    mov si,kn          ; \"KERNEL  SYS\""],
      [134, "    mov cx,11"],
      [135, "    repe cmpsb         ; compare 11 bytes"],
      ["…", ""],
      [145, "fk: mov si,[es:di+26] ; first cluster from dir entry"],
      ["…", ""],
      [171, "ldk:"],
      [172, "    mov dl,[drv]"],
      [173, "    db 0xEA            ; far jmp opcode"],
      [174, "    dw HMA_OFF         ; offset 0x0010"],
      [175, "    dw ENTRY_SEG       ; segment 0x0FFF -> phys 10000h"],
    ],
    hi: [135, 173],
    annotations: [
      [86, "repe cmpsb compares DS:SI (our target name) with ES:DI (the directory entry) byte by byte, CX times, stopping early on a mismatch. CX=11 covers the 8-char name + 3-char extension with no separator."],
      [96, "Offset 26 of a FAT directory entry is the starting cluster number. Everything about reading the file flows from this one 16-bit value."],
      [124, "A hand-assembled far jump: EA + 16-bit offset + 16-bit segment. It loads CS=0x0FFF, IP=0x0010 — the same physical 0x10000 the file was read to, but with the offset matching the kernel's org 0x10 so labels resolve correctly before relocation. DL is reloaded just before so the kernel still knows the boot drive."],
    ],
    regs: [
      ["SI", "cluster #", "walks the FAT chain"],
      ["ES", "1000", "kernel load segment"],
      ["CS:IP", "0FFF:0010", "after the far jump"],
      ["DL", "boot drive", "passed forward"],
    ],
    touches: ["fat", "root", "arena"],
    note: "KERNEL.SYS staged at phys 10000h",
  },
  {
    id: "s2", num: "02", file: "src/kernel.asm", kicker: "Moving day",
    title: "The kernel relocates itself into the HMA",
    prose: [
      "The kernel is assembled with `org 0x10` and was staged at physical 0x10000, but it wants conventional memory free for programs — so it lives in the High Memory Area, the 64 KiB minus 16 bytes at FFFF:0010 that real mode can address once the A20 gate is open. Its first act is to enable A20 (INT 15h AX=2401h, then the keyboard controller, then port 92h, verified each time by a wraparound compare), copy itself up to HMA_SEG, and far-jump into the copy.",
      "The entry point is re-entrant by design: it compares CS against HMA_SEG and only relocates if it isn't already there. After the jump it points every segment register at 0xFFFF, installs the stack at 0xFFF0 — the top of the HMA — and resets the FPU. Low memory keeps only the disk buffers, so the DOS arena can start at 0640h.",
    ],
    code: [
      [121, "kernel_entry:"],
      [122, "    mov ax, cs"],
      [123, "    cmp ax, HMA_SEG        ; already in the HMA?"],
      [124, "    je .relocated"],
      ["…", ""],
      [137, "    call enable_a20"],
      [145, "    mov ax, HMA_SEG"],
      [146, "    mov es, ax"],
      [149, "    mov cx, kernel_end - kernel_entry"],
      [151, "    rep movsb              ; copy kernel -> FFFF:0010"],
      [152, "    jmp HMA_SEG:.relocated"],
      [153, ".relocated:"],
      [157, "    mov ss, ax"],
      [158, "    mov sp, KERNEL_STACK_TOP   ; 0xFFF0"],
      [161, "    fninit"],
    ],
    hi: [136, 151, 157],
    annotations: [
      [122, "CS is read into AX and compared with 0xFFFF. On the first pass CS is still 0x0FFF (the boot sector's staging jump), so the branch falls through into the A20 enable and copy; the second time (post-jump) it's 0xFFFF and we skip straight to .relocated."],
      [136, "enable_a20 tries INT 15h AX=2401h, the keyboard-controller D1/DF sequence, and port 92h fast A20 in turn, after each attempt comparing 16 bytes at 0000:0000 against FFFF:0010 — if they match, writes above 1 MiB still wrap to the IVT and A20 is off. Without A20 the copy below would overwrite the interrupt vector table."],
      [150, "rep movsb copies CX bytes from DS:SI to ES:DI. With CX = kernel_end - kernel_entry, DS=0x0FFF and ES=0xFFFF, the whole kernel image lands at physical 0x100010 — above the 1 MiB line."],
      [151, "The far jump is what actually changes CS to 0xFFFF — until now we were still executing the staged copy at 0x10000. Code can't just `mov cs`; a far jmp/ret is the only way to reload it."],
      [157, "SP is set to 0xFFF0, the top of the HMA. The gap between the kernel image's end and the stack is both stack space and code growth headroom; a compile-time assertion keeps at least 2 KiB of guard between them."],
      [160, "fninit resets the x87 FPU to a known state so later floating-point use (and games that probe for a coprocessor) behave."],
    ],
    regs: [
      ["CS", "FFFF", "after the far jump"],
      ["DS / ES / SS", "FFFF", "all point at the kernel"],
      ["SP", "FFF0", "top of the HMA"],
    ],
    touches: ["kernel"],
    note: "CS = FFFF · SS:SP = FFFF:FFF0 · A20 on",
  },
  {
    id: "s3", num: "03", file: "src/kernel.asm", kicker: "Hello, hardware",
    title: "Bring-up: serial, VGA, memory",
    prose: [
      "With a stack in place the kernel brings up its I/O and takes inventory of memory. Serial comes first because LainDOS logs almost everything over COM1 — it's the project's primary debugging channel — then the VGA text screen is cleared and \"LainDOS booted\" is printed.",
      "Two BIOS calls measure RAM. INT 12h returns conventional memory (the classic ≤640 KiB) in AX; INT 15h/AH=88h returns extended memory above 1 MiB for the XMS shim, capped so the BIOS-backed block move stays under 16 MiB.",
    ],
    code: [
      [163, "    call serial_init"],
      [164, "    call vga_clear"],
      [166, "    mov si, msg_booted     ; \"LainDOS booted\""],
      [167, "    call serial_print"],
      [169, "    int 0x12               ; conventional KiB -> AX"],
      [170, "    mov [mem_kib], ax"],
      ["…", ""],
      [179, "    call init_xms_size     ; INT 15h AH=88h"],
    ],
    hi: [135, 145],
    annotations: [
      [129, "serial_init programs the 8250/16550 UART at port 0x3F8: it sets the divisor latch for the baud rate and configures 8 data bits, no parity, 1 stop bit (8N1). After this, serial_print can poll the line-status register and shift bytes out."],
      [135, "int 0x12 is a BIOS service that takes no inputs and returns the conventional-memory size in KiB in AX (typically 640). It's the simplest possible way to learn how much low RAM exists."],
      [145, "init_xms_size issues INT 15h with AH=88h; the BIOS returns KiB of extended memory in AX. LainDOS subtracts the 64 KiB the kernel occupies as the HMA and clamps the rest so its INT 15h-based XMS block moves never address past 16 MiB."],
    ],
    regs: [
      ["AX", "640", "conventional KiB from INT 12h"],
      ["[mem_kib]", "640", "stashed for AH=… queries"],
      ["[xms_total_kb]", "≤15296", "extended memory for XMS (HMA carved out)"],
    ],
    touches: ["bda", "vga"],
    note: "memory sized · serial live",
  },
  {
    id: "s4", num: "04", file: "src/kernel.asm", kicker: "The vector table",
    title: "Installing the interrupts",
    prose: [
      "This is the moment LainDOS becomes a DOS. The Interrupt Vector Table lives at physical 0 — 256 entries, each a 4-byte far pointer (offset word, then segment word). By writing its own routines into specific slots, the kernel makes the standard DOS software interrupts call its code.",
      "INT 21h is the DOS API itself; INT 20h terminates a program; INT 2Fh is the multiplex used here for XMS and MSCDEX-style CD-ROM probes; INT 33h is the built-in mouse driver. It also claims the CPU fault vectors (01h/06h/0Dh) so a crashing program dumps state over serial instead of hanging silently.",
    ],
    code: [
      [1616, "init_interrupts:"],
      [1620, "    xor ax, ax"],
      [1621, "    mov es, ax            ; ES=0 -> the IVT"],
      [1622, "    mov [es:0x20*4], word int20_handler  ; terminate"],
      [1623, "    mov [es:0x20*4+2], cs"],
      [1624, "    mov [es:0x21*4], word int21_handler  ; DOS API"],
      [1625, "    mov [es:0x21*4+2], cs"],
      [1626, "    mov [es:0x2F*4], word int2f_handler"],
      [1643, "    mov [es:0x33*4], word int33_handler  ; mouse"],
    ],
    hi: [1434, 1435],
    annotations: [
      [1419, "ES is zeroed so ES:offset addresses the IVT at the very bottom of memory. Each vector N is at byte N×4."],
      [1420, "Vector 0x20 (terminate) is at byte 0x80. The low word gets the handler's offset within the kernel segment…"],
      [1421, "…and the high word gets CS (0xFFFF — the kernel runs from the HMA). Together they form the far pointer the CPU jumps to when `int 20h` executes. Every handler is installed as this offset+segment pair."],
      [1422, "INT 21h is the heart of the DOS API — AH selects the function (09h print string, 3Dh open, 3Fh read, 4Ch exit, …). Pointing 0x21 at int21_handler is what lets ordinary DOS programs talk to LainDOS."],
    ],
    regs: [
      ["ES", "0000", "base of the IVT"],
      ["[0:0x21*4]", "int21_handler", "offset of the DOS API"],
      ["[0:0x21*4+2]", "0340", "= CS, the kernel segment"],
    ],
    touches: ["ivt"],
    note: "INT 20h/21h/2Fh/33h live",
  },
  {
    id: "s5", num: "05", file: "src/kernel.asm", kicker: "Carving up RAM",
    title: "Memory arena & filesystem",
    prose: [
      "DOS hands out memory as a chain of Memory Control Blocks — 16-byte headers, each describing the block that follows it. LainDOS seeds the chain with a single block covering everything from 0x1000 up to VGA memory at 0xA000, marked 'Z' (the last/only block) and owner 0 (free).",
      "It then re-validates the BPB the boot sector copied up and derives the on-disk layout: where the FAT starts, where the root directory sits, where the data region begins, and the maximum cluster number — supporting both FAT12 and FAT16 images.",
    ],
    code: [
      [195, "    mov ax, MCB_START      ; 0x1000"],
      [156, "    mov es, ax"],
      [197, "    mov byte [es:0], MCB_SIG_Z   ; 'Z' = last block"],
      [198, "    mov word [es:1], 0           ; owner 0 = free"],
      [199, "    mov ax, MEM_TOP - MCB_START - 1"],
      [200, "    mov word [es:3], ax          ; size in paragraphs"],
      ["…", ""],
      [213, "    call init_bpb_geometry"],
    ],
    hi: [161, 164],
    annotations: [
      [161, "Byte 0 of an MCB is its signature: 'M' means another block follows, 'Z' means it's the last one. A single 'Z' block is the simplest valid arena."],
      [162, "Bytes 1–2 are the owner PSP segment; 0 means free. When a program allocates, this gets stamped with its PSP so the memory can be reclaimed on exit."],
      [164, "Bytes 3–4 hold the block size in 16-byte paragraphs. MEM_TOP − MCB_START − 1 = 0x99BF paragraphs ≈ 614 KiB, the whole conventional arena minus the one-paragraph header."],
      [171, "init_bpb_geometry checks bytes/sector = 512, that sectors-per-cluster is a power of two, and computes krsta/kdsta (FAT and data start) and kmax_cluster, picking FAT12 vs FAT16 from the data-area cluster count (fewer than 4085 clusters means FAT12), as real DOS does."],
    ],
    regs: [
      ["ES", "1000", "points at the first MCB"],
      ["[es:0]", "'Z'", "last block in the chain"],
      ["[es:3]", "99BFh", "free paragraphs (~614K)"],
      ["[mcb_first]", "1000", "head of the MCB chain"],
    ],
    touches: ["arena", "fat", "root"],
    note: "MCB chain armed · BPB validated",
  },
  {
    id: "s6", num: "06", file: "src/kernel.asm", kicker: "MZ or not MZ",
    title: "Finding & sizing the program",
    prose: [
      "Now the kernel loads the program it exists to run. resolve_path locates the boot file by name and returns its directory entry; from there it reads the starting cluster and file size, and pulls the first sector into the sector buffer.",
      "The crucial test is two bytes. DOS executables come in two shapes: a flat .COM image, or a relocatable .EXE that begins with the signature 'MZ'. Read little-endian, those bytes form the word 5A4Dh — one compare decides how much memory to reserve and how the image is laid out.",
    ],
    code: [
      [225, "    mov si, fname_exe"],
      [236, "    call find_in_dir       ; find it in the root"],
      ["…", ""],
      [259, "    mov dx, SEC_BUF"],
      [270, "    mov ds, dx             ; DS -> first sector"],
      [271, "    cmp word [0x0000], 0x5A4D   ; 'MZ' ?"],
      [272, "    je .peek_mz            ; -> EXE path"],
    ],
    hi: [219, 220],
    annotations: [
      [184, "find_in_dir scans the root directory for the 11-byte padded name copied from fname_exe and returns the matching directory entry in ES:DI (or sets carry if not found). The default name comes from -DBOOT_FILE at assembly time (SHELL.COM on this image); user paths go through the full resolve_path component parser instead."],
      [218, "DS is pointed at SEC_BUF (0x0200) so `[0x0000]` reads the very first word of the file we just loaded."],
      [219, "The bytes 'M','Z' are 4Dh,5Ah on disk; little-endian that's the word 0x5A4D. (The format is named after Mark Zbikowski, who designed it.) A match means a header-bearing .EXE…"],
      [220, "…and the EXE path computes minimum/maximum paragraph counts from the header. No match falls through to the COM path, which just reserves the file size plus a fixed slack."],
    ],
    regs: [
      ["ES:DI", "dir entry", "from find_in_dir"],
      ["DS", "0200", "= SEC_BUF, first sector"],
      ["[0]", "5A4Dh?", "'MZ' → EXE, else COM"],
    ],
    touches: ["sec", "root", "arena"],
    note: "image type resolved",
  },
  {
    id: "s7", num: "07", file: "src/kernel.asm", kicker: "Showtime",
    title: "Handoff — the game runs",
    prose: [
      "The kernel allocates a block from the MCB arena, stamps it with the new owner, loads the image cluster-by-cluster just above its Program Segment Prefix, and builds that 256-byte PSP (command tail, environment pointer, default or inherited file handles).",
      "For an .EXE, setup_exe_dyn walks the relocation table — adding the load segment to each flagged word so far pointers resolve correctly — then sets the entry CS:IP and SS:SP from the header and transfers control. For a .COM it simply jumps to offset 0x100. Control won't return until the program calls INT 20h or INT 21h/AH=4Ch.",
    ],
    code: [
      [378, "    mov ax, [cs:prog_seg]"],
      [399, "    call build_psp         ; 256-byte PSP"],
      ["…", ""],
      [398, "    mov ax, [cs:prog_seg]"],
      [417, "    call setup_exe_dyn     ; relocate, set CS:IP/SS:SP, go"],
      ["…", ""],
      ["", "    ; control returns only via INT 20h"],
      ["", "    ; or INT 21h AH=4Ch (terminate)."],
    ],
    hi: [363],
    annotations: [
      [347, "build_psp constructs the Program Segment Prefix at offset 0 of the program's segment: the INT 20h terminate instruction, the top-of-memory word, the environment segment, the command-line tail and the inherited/default handle table. DOS programs expect DS/ES to point here on entry."],
      [363, "setup_exe_dyn applies the .EXE relocations (each is a far-pointer word that needs the actual load segment added), then loads CS:IP and SS:SP from the header and jumps. The very next thing on screen is the program's own output — for the demo image, the SHELL.COM prompt. Run `midemo` from there to start Monkey Island."],
    ],
    regs: [
      ["CS:IP", "entry point", "from the EXE header"],
      ["SS:SP", "program stack", "from the EXE header"],
      ["DS / ES", "PSP segment", "DOS calling convention"],
    ],
    touches: ["arena", "vga"],
    note: "program owns the CPU",
    payoff: true,
  },
];

const RUN_TRIES = [
  { k: "Boot the demo", v: "The image boots to SHELL.COM; type `midemo` at the prompt to start the Monkey Island demo." },
  { k: "Watch the serial log", v: "LainDOS narrates boot + INT 21h calls over COM1 — flip to the Serial tab to read the boot you just walked through, live." },
  { k: "Use the shell", v: "Once the demo exits, you land in SHELL.COM — try DIR, CD, SET, or MEM." },
];

Object.assign(window, { NAV, MEMMAP, STAGES, RUN_TRIES });
